name: Python CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_py_3_7:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow
        pip install torch torchvision
        pip install flake8 pytest
        pip install .

    - name: Lint with flake8
      run: |
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Tests
      run: |
        pytest

  test_py3_12:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow
        pip install torch torchvision
        pip install flake8 pytest
        pip install .

    - name: Run Tests
      run: |
        pytest

